const { createClient } = require('@supabase/supabase-js');

const url = 'https://jkdexnctchzprkbdbsnq.supabase.co';
const key = 'sb_publishable_WC5vC3p-iaYxNvef8dpgXQ_kNKTed-9';

const supabase = createClient(url, key);

// 85+ High Quality Realistic E-Commerce Products across 6 Categories
const PRODUCTS_DATA = [
  // -------------------------------------------------------------
  // ELECTRONICS (Category 1) - 20 items
  // -------------------------------------------------------------
  {
    name: 'Apple iPhone 15 Pro (128GB, Natural Titanium)',
    brand: 'Apple',
    category_id: 1,
    price: 999.00,
    discount: 10,
    rating: 4.8,
    stock: 45,
    description: 'Forged in titanium with A17 Pro chip, customizable Action button, and powerful 48MP camera system.',
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Samsung Galaxy S24 Ultra (512GB, Titanium Black)',
    brand: 'Samsung',
    category_id: 1,
    price: 1199.99,
    discount: 12,
    rating: 4.7,
    stock: 30,
    description: 'Galaxy AI is here. Epic camera with 200MP detail, built-in S Pen, and Snapdragon 8 Gen 3 for Galaxy.',
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    brand: 'Sony',
    category_id: 1,
    price: 398.00,
    discount: 15,
    rating: 4.9,
    stock: 60,
    description: 'Industry-leading noise canceling with two processors and 8 microphones. Up to 30-hour battery life.',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Apple AirPods Pro 2nd Gen with USB-C',
    brand: 'Apple',
    category_id: 1,
    price: 249.00,
    discount: 8,
    rating: 4.8,
    stock: 80,
    description: 'Active Noise Cancellation, Adaptive Audio, Transparency mode, and Personalized Spatial Audio.',
    image_url: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dell XPS 13 Touchscreen Laptop (16GB RAM, 512GB SSD)',
    brand: 'Dell',
    category_id: 1,
    price: 1299.99,
    discount: 15,
    rating: 4.6,
    stock: 25,
    description: 'Stunning FHD+ display, Intel Core Ultra 7 processor, machined aluminum chassis, ultra-lightweight.',
    image_url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Apple MacBook Air M3 (15-inch, 8GB RAM, 256GB SSD)',
    brand: 'Apple',
    category_id: 1,
    price: 1299.00,
    discount: 5,
    rating: 4.9,
    stock: 40,
    description: 'Supercharged by M3 chip, incredibly thin design, up to 18 hours of battery life, Liquid Retina display.',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Bose SoundLink Flex Bluetooth Speaker',
    brand: 'Bose',
    category_id: 1,
    price: 149.00,
    discount: 20,
    rating: 4.7,
    stock: 75,
    description: 'PositionIQ technology automatically detects orientation to optimize sound quality anywhere.',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    brand: 'Logitech',
    category_id: 1,
    price: 99.99,
    discount: 10,
    rating: 4.8,
    stock: 90,
    description: 'Quiet clicks, 8K DPI track-on-glass sensor, MagSpeed electromagnetic scrolling wheel.',
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Keychron K2 Pro Mechanical Wireless Keyboard',
    brand: 'Keychron',
    category_id: 1,
    price: 119.99,
    discount: 12,
    rating: 4.7,
    stock: 50,
    description: 'QMK/VIA wireless mechanical keyboard with hot-swappable switches and double-shot PBT keycaps.',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'LG UltraGear 27-inch QHD Gaming Monitor 165Hz',
    brand: 'LG',
    category_id: 1,
    price: 299.99,
    discount: 25,
    rating: 4.6,
    stock: 35,
    description: '1ms response time, Nano IPS panel, NVIDIA G-SYNC compatible, HDR 400 vivid color accuracy.',
    image_url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Anker 737 Power Bank 24,000mAh (140W Output)',
    brand: 'Anker',
    category_id: 1,
    price: 139.99,
    discount: 18,
    rating: 4.8,
    stock: 100,
    description: 'Ultra-powerful two-way charging with smart digital display and Power Delivery 3.1 technology.',
    image_url: 'https://images.unsplash.com/photo-1609592424074-124b8989c445?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Canon EOS R6 Mark II Mirrorless Camera',
    brand: 'Canon',
    category_id: 1,
    price: 2499.00,
    discount: 10,
    rating: 4.9,
    stock: 15,
    description: '24.2MP full-frame CMOS sensor, 40 fps continuous shooting, Dual Pixel CMOS AF II with vehicle detection.',
    image_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm Aluminum',
    brand: 'Apple',
    category_id: 1,
    price: 429.00,
    discount: 15,
    rating: 4.8,
    stock: 55,
    description: 'S9 SiP chip enable double-tap gesture, brighter Retina display, faster Siri processing on device.',
    image_url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'ASUS ROG Ally Handheld Gaming Console',
    brand: 'ASUS',
    category_id: 1,
    price: 699.99,
    discount: 10,
    rating: 4.5,
    stock: 20,
    description: 'AMD Z1 Extreme processor, 7-inch 120Hz FHD touchscreen display, Windows 11 gaming portability.',
    image_url: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'JBL Flip 6 Waterproof Portable Bluetooth Speaker',
    brand: 'JBL',
    category_id: 1,
    price: 129.95,
    discount: 23,
    rating: 4.7,
    stock: 85,
    description: 'Bold sound for every adventure, 2-way speaker system, IP67 waterproof and dustproof design.',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Kindle Paperwhite 16GB (6.8" Display, Adjustable Warm Light)',
    brand: 'Amazon',
    category_id: 1,
    price: 149.99,
    discount: 15,
    rating: 4.8,
    stock: 65,
    description: '300 ppi glare-free display, waterproof rating IPX8, up to 10 weeks of battery life on a single charge.',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'GoPro HERO12 Black Action Camera',
    brand: 'GoPro',
    category_id: 1,
    price: 399.99,
    discount: 20,
    rating: 4.6,
    stock: 40,
    description: 'Incredible 5.3K60 video, HDR video & photo, HyperSmooth 6.0 video stabilization, bluetooth audio support.',
    image_url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Belkin 3-in-1 Wireless MagSafe Charging Stand',
    brand: 'Belkin',
    category_id: 1,
    price: 149.99,
    discount: 10,
    rating: 4.7,
    stock: 50,
    description: '15W fast wireless charging for iPhone 15/14/13, Apple Watch Series 9, and AirPods Pro.',
    image_url: 'https://images.unsplash.com/photo-1609592424074-124b8989c445?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Razer DeathAdder V3 Pro Gaming Mouse',
    brand: 'Razer',
    category_id: 1,
    price: 149.99,
    discount: 14,
    rating: 4.7,
    stock: 60,
    description: 'Ultra-lightweight 63g ergonomic design, Focus Pro 30K optical sensor, Gen-3 optical mouse switches.',
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Samsung T7 Shield 2TB Portable External SSD',
    brand: 'Samsung',
    category_id: 1,
    price: 169.99,
    discount: 20,
    rating: 4.9,
    stock: 70,
    description: 'Rugged USB 3.2 Gen 2 speed up to 1,050 MB/s, IP65 water & dust resistance, drop-resistant up to 9.8ft.',
    image_url: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------------
  // FASHION (Category 2) - 20 items
  // -------------------------------------------------------------
  {
    name: 'Classic Levi\'s 501 Original Fit Denim Jeans',
    brand: "Levi's",
    category_id: 2,
    price: 79.50,
    discount: 25,
    rating: 4.6,
    stock: 90,
    description: 'The original blue jean since 1873. Straight fit featuring iconic button fly and timeless style.',
    image_url: 'https://images.unsplash.com/photo-1542272604-780c36856842?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Uniqlo AIRism Cotton Oversized Crew Neck T-Shirt',
    brand: 'Uniqlo',
    category_id: 2,
    price: 29.90,
    discount: 10,
    rating: 4.8,
    stock: 120,
    description: 'Smooth cotton exterior with high-performance AIRism interior. Breathable and relaxed modern fit.',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Zara Tailored Double-Breasted Wool Blend Coat',
    brand: 'Zara',
    category_id: 2,
    price: 159.00,
    discount: 30,
    rating: 4.7,
    stock: 35,
    description: 'Sophisticated lapel collar coat with padded shoulders, front flap pockets, and back vent.',
    image_url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Patagonia Better Sweater Fleece Jacket',
    brand: 'Patagonia',
    category_id: 2,
    price: 149.00,
    discount: 15,
    rating: 4.9,
    stock: 50,
    description: 'Warm 100% recycled polyester fleece sweater with sweater-knit aesthetic and low-impact dyeing process.',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'H&M Relaxed Linen-Blend Casual Shirt',
    brand: 'H&M',
    category_id: 2,
    price: 34.99,
    discount: 20,
    rating: 4.5,
    stock: 85,
    description: 'Soft linen and cotton blend weave with turn-down collar, classic front button placket, and curved hem.',
    image_url: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Calvin Klein Lightweight Down Puffer Jacket',
    brand: 'Calvin Klein',
    category_id: 2,
    price: 180.00,
    discount: 40,
    rating: 4.7,
    stock: 40,
    description: 'Packable wind-resistant shell insulation with side zip pockets and signature CK logo crest.',
    image_url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Tommy Hilfiger Essential Polo Shirt',
    brand: 'Tommy Hilfiger',
    category_id: 2,
    price: 69.50,
    discount: 20,
    rating: 4.6,
    stock: 75,
    description: 'Pure breathable cotton piqué knit polo shirt with two-button placket and signature flag embroidery.',
    image_url: 'https://images.unsplash.com/photo-1625910513413-7221355486fd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mango Flowy Printed Wrap Midi Dress',
    brand: 'Mango',
    category_id: 2,
    price: 89.99,
    discount: 25,
    rating: 4.7,
    stock: 45,
    description: 'Elegantly draped floral wrap dress with V-neckline, puff elbow sleeves, and tied waist sash.',
    image_url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Champion Reverse Weave Heavyweight Hoodie',
    brand: 'Champion',
    category_id: 2,
    price: 65.00,
    discount: 15,
    rating: 4.8,
    stock: 95,
    description: 'Durable cross-grain fleece construction cut to resist vertical shrinkage, fleece-lined hood.',
    image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ray-Ban Wayfarer Classic Polarized Sunglasses',
    brand: 'Ray-Ban',
    category_id: 2,
    price: 171.00,
    discount: 15,
    rating: 4.9,
    stock: 60,
    description: 'The most recognizable style in sunglasses history. Crystal green polarized lenses offer 100% UV protection.',
    image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Fossil Minimalist Stainless Steel Quartz Watch',
    brand: 'Fossil',
    category_id: 2,
    price: 130.00,
    discount: 30,
    rating: 4.6,
    stock: 50,
    description: 'Clean satin dial with stick indices, durable mineral crystal, and mesh stainless steel strap.',
    image_url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Michael Kors Jet Set Large Crossbody Leather Bag',
    brand: 'Michael Kors',
    category_id: 2,
    price: 198.00,
    discount: 35,
    rating: 4.8,
    stock: 35,
    description: 'Structured saffiano leather silhouette with chain-link accents and secure zip-top closure.',
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'The North Face Resolve 2 Waterproof Jacket',
    brand: 'The North Face',
    category_id: 2,
    price: 99.00,
    discount: 15,
    rating: 4.7,
    stock: 70,
    description: 'DryVent 2L seam-sealed waterproof rain jacket with adjustable stowable hood and mesh lining.',
    image_url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ralph Lauren Classic Fit Oxford Button-Down Shirt',
    brand: 'Ralph Lauren',
    category_id: 2,
    price: 110.00,
    discount: 20,
    rating: 4.8,
    stock: 60,
    description: 'Iconic durable cotton oxford cloth tailored with signature embroidered pony emblem on chest.',
    image_url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Adidas Essentials 3-Stripes Track Pants',
    brand: 'Adidas',
    category_id: 2,
    price: 50.00,
    discount: 18,
    rating: 4.6,
    stock: 110,
    description: 'Tapered legs with ribbed cuffs and drawcord elastic waist. Soft knit fabric for everyday comfort.',
    image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Herschel Supply Co. Little America Backpack',
    brand: 'Herschel',
    category_id: 2,
    price: 120.00,
    discount: 15,
    rating: 4.8,
    stock: 80,
    description: 'Mountaineering-inspired silhouette with fleece-lined 15-inch laptop sleeve and magnetic strap closures.',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Lululemon Align High-Rise Leggings 25"',
    brand: 'Lululemon',
    category_id: 2,
    price: 98.00,
    discount: 10,
    rating: 4.9,
    stock: 65,
    description: 'Powered by buttery-soft Nulu fabric. Weightless feel, sweat-wicking four-way stretch comfort.',
    image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Bellroy Leather Slim Sleeve Bifold Wallet',
    brand: 'Bellroy',
    category_id: 2,
    price: 79.00,
    discount: 12,
    rating: 4.7,
    stock: 75,
    description: 'Environmentally certified leather wallet designed for quick card access and slim pocket profile.',
    image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Barbour Classic Bedale Waxed Cotton Jacket',
    brand: 'Barbour',
    category_id: 2,
    price: 395.00,
    discount: 15,
    rating: 4.9,
    stock: 20,
    description: 'Authentic mediumweight 6oz Thornproof wax exterior with tartan cotton lining and corduroy collar.',
    image_url: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Oakley Holbrook Prizm Matte Black Sunglasses',
    brand: 'Oakley',
    category_id: 2,
    price: 156.00,
    discount: 20,
    rating: 4.7,
    stock: 45,
    description: 'Prizm lens technology designed to enhance color and contrast for high-definition visual clarity.',
    image_url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------------
  // SHOES (Category 3) - 15 items
  // -------------------------------------------------------------
  {
    name: 'Nike Air Max 270 Running Shoes',
    brand: 'Nike',
    category_id: 3,
    price: 160.00,
    discount: 15,
    rating: 4.8,
    stock: 85,
    description: 'Nike\'s biggest heel Max Air unit delivers super-soft bounce with breathable mesh upper comfort.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes',
    brand: 'Adidas',
    category_id: 3,
    price: 190.00,
    discount: 20,
    rating: 4.9,
    stock: 60,
    description: 'Lightest Ultraboost ever made. Epic energy return powered by Light BOOST material and Primeknit+ upper.',
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Puma Velocity Nitro 2 Cushion Running Shoes',
    brand: 'Puma',
    category_id: 3,
    price: 130.00,
    discount: 25,
    rating: 4.6,
    stock: 70,
    description: 'All-in-one neutral running shoe for any distance. Nitrogen-infused NITRO foam responsively cushions feet.',
    image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'New Balance 574 Core Classic Lifestyle Sneakers',
    brand: 'New Balance',
    category_id: 3,
    price: 89.99,
    discount: 10,
    rating: 4.7,
    stock: 95,
    description: 'ENCAP midsole technology delivers lightweight cushioning with durable suede and mesh upper.',
    image_url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Converse Chuck Taylor All Star High Top Sneakers',
    brand: 'Converse',
    category_id: 3,
    price: 65.00,
    discount: 10,
    rating: 4.8,
    stock: 130,
    description: 'Timeless canvas upper high top silhouette featuring star ankle patch and vulcanized rubber outsole.',
    image_url: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Vans Old Skool Core Classic Skate Shoes',
    brand: 'Vans',
    category_id: 3,
    price: 70.00,
    discount: 12,
    rating: 4.7,
    stock: 110,
    description: 'Iconic side stripe skate shoe with sturdy suede/canvas uppers, re-enforced toe caps, and signature rubber waffle outsoles.',
    image_url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Clarks Bushacre 2 Leather Chukka Boots',
    brand: 'Clarks',
    category_id: 3,
    price: 110.00,
    discount: 30,
    rating: 4.5,
    stock: 45,
    description: 'Versatile ankle-height boot featuring premium leather, contrast stitching, and synthetic crepe outsole.',
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dr. Martens 1460 Smooth Leather 8-Eye Boots',
    brand: 'Dr. Martens',
    category_id: 3,
    price: 170.00,
    discount: 15,
    rating: 4.8,
    stock: 40,
    description: 'Original Dr. Martens boot built with yellow welt stitching, grooved sides, and air-cushioned sole.',
    image_url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Timberland 6-Inch Premium Waterproof Boots',
    brand: 'Timberland',
    category_id: 3,
    price: 198.00,
    discount: 18,
    rating: 4.8,
    stock: 50,
    description: 'Seam-sealed waterproof construction using nubuck leather and 400 grams of PrimaLoft insulation.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Birkenstock Arizona Birko-Flor Sandals',
    brand: 'Birkenstock',
    category_id: 3,
    price: 110.00,
    discount: 10,
    rating: 4.7,
    stock: 80,
    description: 'Iconic two-strap sandal with anatomically shaped cork-latex footbed that contours to foot shape.',
    image_url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'On Cloud 5 Lightweight Daily Running Shoes',
    brand: 'On',
    category_id: 3,
    price: 139.99,
    discount: 10,
    rating: 4.9,
    stock: 75,
    description: 'CloudTec in Zero-Gravity foam provides soft cushioned landings with speed lacing system convenience.',
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Asics Gel-Kayano 30 Stability Running Shoes',
    brand: 'Asics',
    category_id: 3,
    price: 160.00,
    discount: 20,
    rating: 4.8,
    stock: 55,
    description: '4D GUIDANCE SYSTEM technology provides adaptive stability for marathon running and training.',
    image_url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Salomon Speedcross 6 Trail Running Shoes',
    brand: 'Salomon',
    category_id: 3,
    price: 145.00,
    discount: 15,
    rating: 4.7,
    stock: 35,
    description: 'Deep aggressive lugs grip muddy trails, Sensifit upper construction cradles foot securely.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Crocs Classic Clog Slip-On Water Shoes',
    brand: 'Crocs',
    category_id: 3,
    price: 49.99,
    discount: 20,
    rating: 4.6,
    stock: 140,
    description: 'Lightweight Croslite material offering iconic comfort, ventilation ports, and pivoting heel straps.',
    image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Skechers Arch Fit Banlin Slip-On Walking Shoes',
    brand: 'Skechers',
    category_id: 3,
    price: 85.00,
    discount: 15,
    rating: 4.5,
    stock: 90,
    description: 'Podiatrist-certified arch support system combined with air-cooled removable cushioned insole.',
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------------
  // BEAUTY (Category 4) - 15 items
  // -------------------------------------------------------------
  {
    name: 'HydraGlow Hyaluronic Acid Face Serum (30ml)',
    brand: 'The Ordinary',
    category_id: 4,
    price: 18.50,
    discount: 10,
    rating: 4.7,
    stock: 150,
    description: 'Multi-depth hydration formula targeting fine lines and plumpness with multi-molecular hyaluronic acid.',
    image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'La Roche-Posay Anthelios Ultra Light SPF 60 Sunscreen',
    brand: 'La Roche-Posay',
    category_id: 4,
    price: 34.99,
    discount: 15,
    rating: 4.9,
    stock: 100,
    description: 'Cell-Ox Shield technology combines broad spectrum UVA/UVB protection with powerful antioxidants.',
    image_url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin',
    brand: 'CeraVe',
    category_id: 4,
    price: 16.99,
    discount: 12,
    rating: 4.8,
    stock: 120,
    description: 'Non-foaming lotion cleanser formulated with essential ceramides 1, 3, 6-II and hyaluronic acid.',
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Estée Lauder Advanced Night Repair Serum (50ml)',
    brand: 'Estée Lauder',
    category_id: 4,
    price: 115.00,
    discount: 20,
    rating: 4.8,
    stock: 45,
    description: 'Patented Chronolux Power Signal Technology repairs skin texture and restores radiance while sleeping.',
    image_url: 'https://images.unsplash.com/photo-1608248597263-00079e964474?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'MAC Velvet Matte Lipstick (Ruby Woo Red)',
    brand: 'MAC',
    category_id: 4,
    price: 23.00,
    discount: 10,
    rating: 4.9,
    stock: 110,
    description: 'Iconic vivid blue-red matte lipstick formulation delivering full coverage and 10-hour wear.',
    image_url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Fenty Beauty Pro Filt\'r Soft Matte Longwear Foundation',
    brand: 'Fenty Beauty',
    category_id: 4,
    price: 40.00,
    discount: 15,
    rating: 4.7,
    stock: 80,
    description: 'Soft matte oil-free foundation with climate-adaptive technology resistant to sweat and shine.',
    image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dior Sauvage Eau de Parfum Spray (100ml)',
    brand: 'Dior',
    category_id: 4,
    price: 145.00,
    discount: 12,
    rating: 4.9,
    stock: 50,
    description: 'A powerful sensual fragrance trail of Calabrian bergamot and Papua New Guinean vanilla absolute.',
    image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Chanel Coco Mademoiselle Eau de Parfum (50ml)',
    brand: 'Chanel',
    category_id: 4,
    price: 138.00,
    discount: 10,
    rating: 4.9,
    stock: 40,
    description: 'An amber fragrance with a strong character and surprising freshness. Vibrant orange notes blend with jasmine.',
    image_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Olaplex No. 3 Hair Perfector Repairing Treatment',
    brand: 'Olaplex',
    category_id: 4,
    price: 30.00,
    discount: 15,
    rating: 4.8,
    stock: 95,
    description: 'Weekly at-home bond-building treatment that reduces breakage and visibly strengthens damaged hair.',
    image_url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Paula\'s Choice 2% BHA Liquid Salicylic Acid Exfoliant',
    brand: "Paula's Choice",
    category_id: 4,
    price: 35.00,
    discount: 15,
    rating: 4.8,
    stock: 85,
    description: 'Unclogs pores, smoothes wrinkles, and brightens uneven skin tone gently with leave-on salicylic acid.',
    image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sol de Janeiro Brazilian Bum Bum Firming Cream (240ml)',
    brand: 'Sol de Janeiro',
    category_id: 4,
    price: 48.00,
    discount: 10,
    rating: 4.8,
    stock: 70,
    description: 'Fast-absorbing body cream infused with caffeine-rich Guaraná extract for visibly tighter skin.',
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Urban Decay Naked2 Basics Eyeshadow Palette',
    brand: 'Urban Decay',
    category_id: 4,
    price: 35.00,
    discount: 20,
    rating: 4.7,
    stock: 65,
    description: 'Six taupe-hued neutral matte eyeshadows featuring velvety texture, rich color, and smooth blendability.',
    image_url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Kiehl\'s Ultra Facial Cream with Squalane (50ml)',
    brand: "Kiehl's",
    category_id: 4,
    price: 38.00,
    discount: 10,
    rating: 4.8,
    stock: 75,
    description: 'Lightweight 24-hour facial moisturizer providing 2.3X hydration even in skin\'s driest areas.',
    image_url: 'https://images.unsplash.com/photo-1608248597263-00079e964474?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Maybelline Lash Sensational Washable Mascara',
    brand: 'Maybelline',
    category_id: 4,
    price: 11.99,
    discount: 15,
    rating: 4.6,
    stock: 160,
    description: 'Exclusive fanning brush with 10 layers of bristles reveals full fan lash effect without clumping.',
    image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Laneige Lip Sleeping Mask (Berry Flavor 20g)',
    brand: 'Laneige',
    category_id: 4,
    price: 24.00,
    discount: 10,
    rating: 4.9,
    stock: 130,
    description: 'Overnight leave-on lip mask enriched with Berry Mix Complex and vitamin C to soothe dry lips.',
    image_url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------------
  // HOME (Category 5) - 15 items
  // -------------------------------------------------------------
  {
    name: 'Nespresso VertuoPlus Coffee & Espresso Machine',
    brand: 'Nespresso',
    category_id: 5,
    price: 169.00,
    discount: 20,
    rating: 4.7,
    stock: 40,
    description: 'Centrifusion technology reads barcode on capsule to brew single-serve coffee or crema-rich espresso.',
    image_url: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ninja AF101 Air Fryer (4-Quart Capacity)',
    brand: 'Ninja',
    category_id: 5,
    price: 99.99,
    discount: 23,
    rating: 4.8,
    stock: 70,
    description: 'Crisp, roast, reheat, and dehydrate foods using up to 75% less fat than traditional frying methods.',
    image_url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dyson V12 Detect Slim Cordless Vacuum Cleaner',
    brand: 'Dyson',
    category_id: 5,
    price: 649.99,
    discount: 15,
    rating: 4.8,
    stock: 25,
    description: 'Illuminating laser reveals microscopic dust on hard floors. Intelligently adapts suction power based on floor type.',
    image_url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Le Creuset Enameled Cast Iron Dutch Oven (5.5-Qt)',
    brand: 'Le Creuset',
    category_id: 5,
    price: 419.95,
    discount: 10,
    rating: 4.9,
    stock: 20,
    description: 'Iconic French culinary cookware engineered for optimal heat distribution and retention.',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6-Qt',
    brand: 'Instant Pot',
    category_id: 5,
    price: 89.99,
    discount: 25,
    rating: 4.7,
    stock: 80,
    description: 'Combines pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Philips Hue White & Color Ambiance Starter Kit',
    brand: 'Philips',
    category_id: 5,
    price: 179.99,
    discount: 15,
    rating: 4.6,
    stock: 50,
    description: 'Smart LED bulbs offer 16 million colors and sync with movies, music, and games via Hue Bridge.',
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ceramic Modern Dining Table Set with 4 Chairs',
    brand: 'IKEA',
    category_id: 5,
    price: 349.00,
    discount: 20,
    rating: 4.6,
    stock: 15,
    description: 'Sleek ceramic tabletop with scratch-resistant coating and ergonomic padded Scandinavian chairs.',
    image_url: 'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Brooklinen Organic Cotton 4-Piece Sheet Set (Queen)',
    brand: 'Brooklinen',
    category_id: 5,
    price: 159.00,
    discount: 15,
    rating: 4.8,
    stock: 60,
    description: 'Long-staple 100% organic cotton percale weave with crisp, breathable matte finish for hot sleepers.',
    image_url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'COSORI Stainless Steel Dehydrator & Food Steamer',
    brand: 'COSORI',
    category_id: 5,
    price: 159.99,
    discount: 20,
    rating: 4.7,
    stock: 45,
    description: '6 stainless steel trays, precise temperature controls, quiet operation for jerky, fruit leather, and herbs.',
    image_url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Modern Industrial Floor Lamp with Glass Shade',
    brand: 'West Elm',
    category_id: 5,
    price: 199.00,
    discount: 25,
    rating: 4.6,
    stock: 30,
    description: 'Matte black metal stem topped with hand-blown clear glass globe shade and foot switch control.',
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Keurig K-Elite Single Serve Coffee Maker',
    brand: 'Keurig',
    category_id: 5,
    price: 129.99,
    discount: 30,
    rating: 4.6,
    stock: 65,
    description: 'Strong brew feature increases coffee intensity, iced setting brews hot over ice for iced coffee.',
    image_url: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'KitchenAid Artisan Series 5-Quart Stand Mixer',
    brand: 'KitchenAid',
    category_id: 5,
    price: 449.99,
    discount: 10,
    rating: 4.9,
    stock: 25,
    description: '10 speed controls, tilt-head design, stainless steel bowl with comfortable handle, includes flat beater & dough hook.',
    image_url: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Boll & Branch Signature Hemmed Duvet Cover Set',
    brand: 'Boll & Branch',
    category_id: 5,
    price: 278.00,
    discount: 15,
    rating: 4.9,
    stock: 35,
    description: 'Crafted from 100% organic long-staple cotton for buttery softness that gets softer with every wash.',
    image_url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Honey-Can-Do 3-Tier Bamboo Utility Cart with Wheels',
    brand: 'Honey-Can-Do',
    category_id: 5,
    price: 69.99,
    discount: 20,
    rating: 4.5,
    stock: 75,
    description: 'Eco-friendly solid bamboo construction with rolling caster wheels for portable kitchen or bathroom storage.',
    image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Levoit Core 300 Smart HEPA Air Purifier',
    brand: 'Levoit',
    category_id: 5,
    price: 99.99,
    discount: 15,
    rating: 4.8,
    stock: 90,
    description: 'H13 True HEPA filter captures 99.97% of airborne particles 0.3 microns size. Ultra-quiet sleep mode.',
    image_url: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',
  },

  // -------------------------------------------------------------
  // SPORTS (Category 6) - 15 items
  // -------------------------------------------------------------
  {
    name: 'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
    brand: 'Bowflex',
    category_id: 6,
    price: 429.00,
    discount: 20,
    rating: 4.8,
    stock: 30,
    description: 'Adjusts from 5 to 52.5 lbs in 2.5 lb increments with intuitive dial selection system.',
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Manduka PRO Yoga Mat (6mm Thick High Density)',
    brand: 'Manduka',
    category_id: 6,
    price: 138.00,
    discount: 10,
    rating: 4.9,
    stock: 70,
    description: 'Ultra-dense cushioning supports joints, closed-cell surface prevents moisture and sweat from seeping.',
    image_url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Garmin Forerunner 265 GPS Running Smartwatch',
    brand: 'Garmin',
    category_id: 6,
    price: 449.99,
    discount: 12,
    rating: 4.8,
    stock: 40,
    description: 'Colorful AMOLED display, morning report, HRV status, workout readiness, up to 13 days battery life.',
    image_url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hydro Flask 32 oz Wide Mouth Insulated Water Bottle',
    brand: 'Hydro Flask',
    category_id: 6,
    price: 44.95,
    discount: 15,
    rating: 4.9,
    stock: 120,
    description: 'TempShield double-wall vacuum insulation keeps drinks cold up to 24 hours or hot up to 12 hours.',
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'TRX All-in-One Bodyweight Suspension Trainer Kit',
    brand: 'TRX',
    category_id: 6,
    price: 179.95,
    discount: 18,
    rating: 4.7,
    stock: 55,
    description: 'Full body workout system anchors to doors or rafters. Build core strength, endurance, and mobility.',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Spalding TF-1000 Legacy Indoor Basketball (Size 7)',
    brand: 'Spalding',
    category_id: 6,
    price: 74.99,
    discount: 15,
    rating: 4.7,
    stock: 65,
    description: 'Microfiber composite leather cover provides soft grip and true bounce for high school and collegiate play.',
    image_url: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Wilson Pro Staff 97 v14 Tennis Racket',
    brand: 'Wilson',
    category_id: 6,
    price: 279.00,
    discount: 10,
    rating: 4.8,
    stock: 25,
    description: 'Braid 45 construction places double-braided fibers at 45-degree angles for enhanced feel and stability.',
    image_url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Theragun PRO Percussive Therapy Deep Tissue Massager',
    brand: 'Therabody',
    category_id: 6,
    price: 599.00,
    discount: 25,
    rating: 4.8,
    stock: 20,
    description: 'Commercial-grade deep muscle treatment with quiet EQ Technology, 16mm amplitude, and OLED screen.',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Titleist Pro V1 Golf Balls (One Dozen)',
    brand: 'Titleist',
    category_id: 6,
    price: 54.99,
    discount: 10,
    rating: 4.9,
    stock: 100,
    description: 'The #1 ball in golf. Extraordinary distance, high trajectory, low long game spin, and Drop-and-Stop control.',
    image_url: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Gaiam Resistance Band Set of 3 Loop Bands',
    brand: 'Gaiam',
    category_id: 6,
    price: 19.99,
    discount: 20,
    rating: 4.6,
    stock: 130,
    description: 'Light, medium, and heavy resistance fabric bands designed for hip, glute, and lower body activation.',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Peloton Bike+ Indoor Exercise Stationary Bike',
    brand: 'Peloton',
    category_id: 6,
    price: 2495.00,
    discount: 15,
    rating: 4.8,
    stock: 10,
    description: 'Rotating 23.8" HD touchscreen, Auto-Follow resistance digital knob, stereo speakers with 8-channel audio.',
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Speedo Vanquisher 2.0 Mirrored Swim Goggles',
    brand: 'Speedo',
    category_id: 6,
    price: 24.99,
    discount: 15,
    rating: 4.7,
    stock: 110,
    description: 'Precision fit cushioned silicone seals, panoramic mirrored lenses reduce glare in bright open water.',
    image_url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'CamelBak Mule 12 oz Hydration Backpack (100oz Reservoir)',
    brand: 'CamelBak',
    category_id: 6,
    price: 115.00,
    discount: 15,
    rating: 4.8,
    stock: 45,
    description: 'Crux 3L reservoir delivers 20% more water per sip. Air Director back panel keeps riders cool.',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Under Armour Men\'s Tech 2.0 Short Sleeve T-Shirt',
    brand: 'Under Armour',
    category_id: 6,
    price: 25.00,
    discount: 10,
    rating: 4.7,
    stock: 150,
    description: 'UA Tech fabric is quick-drying, ultra-soft & has a more natural feel. Material wicks sweat & dries fast.',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Fitbit Charge 6 Fitness Tracker with Google Apps',
    brand: 'Fitbit',
    category_id: 6,
    price: 159.95,
    discount: 20,
    rating: 4.6,
    stock: 60,
    description: 'Built-in GPS, 40+ exercise modes, ECG app, YouTube Music controls, and 7-day battery life.',
    image_url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
  }
];

async function seedDatabase() {
  console.log('--- SEEDING SHOPAI DATABASE ---');

  // Authenticate as Admin user
  const email = 'admin@shopai.com';
  const password = 'AdminPassword123!';

  const { data: authData, error: authErr } = await supabase.auth.signInWithPassword({ email, password });
  if (authErr || !authData?.session) {
    console.error('Failed to log in as admin:', authErr);
    return;
  }

  await supabase.auth.setSession({
    access_token: authData.session.access_token,
    refresh_token: authData.session.refresh_token,
  });

  console.log('Authenticated session set for admin:', authData.user.id);

  // 1. Fetch existing product names to avoid duplicates
  const { data: existingProducts, error: prodErr } = await supabase.from('products').select('name');
  if (prodErr) {
    console.error('Error fetching existing products:', prodErr);
    return;
  }

  const existingNames = new Set((existingProducts || []).map((p) => p.name.toLowerCase()));
  console.log(`Currently ${existingNames.size} existing products in DB.`);

  // 2. Filter products to insert
  const toInsert = PRODUCTS_DATA.filter((p) => !existingNames.has(p.name.toLowerCase()));

  console.log(`Preparing to insert ${toInsert.length} new unique products...`);

  if (toInsert.length === 0) {
    console.log('Database already has all seeded products!');
  } else {
    // Insert in batches of 10
    const batchSize = 10;
    for (let i = 0; i < toInsert.length; i += batchSize) {
      const batch = toInsert.slice(i, i + batchSize);
      const { data, error } = await supabase.from('products').insert(batch).select('id');
      if (error) {
        console.error(`Batch insert error [${i}..${i + batchSize}]:`, error.message);
      } else {
        console.log(`Batch [${i}..${i + batch.length}] inserted successfully. Added ${data.length} items.`);
      }
    }
  }

  // 3. Verify total count after seeding
  const { count: finalCount, error: countErr } = await supabase.from('products').select('*', { count: 'exact', head: true });
  if (countErr) {
    console.error('Error fetching final count:', countErr.message);
  } else {
    console.log(`\n🎉 SUCCESS! Total Products now in Supabase Database: ${finalCount}`);
  }
}

seedDatabase().catch(console.error);
