import React from 'react';
import { BarChart3, TrendingUp, Cpu, DollarSign } from 'lucide-react';
import { useAdminStats } from '../../hooks/useAdminStats';

export const AnalyticsPage: React.FC = () => {
  const { stats } = useAdminStats();

  return (
    <div className="space-y-8 pb-12">
      <div className="pb-4 border-b border-slate-800">
        <h1 className="text-2xl font-bold text-white tracking-tight">Analytics & Insights</h1>
        <p className="text-xs text-slate-400 mt-1">Platform performance metrics & AI match metrics</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
          <div className="flex justify-between items-center text-indigo-400">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Avg Order Value
            </span>
            <DollarSign className="w-5 h-5" />
          </div>
          <h2 className="text-2xl font-extrabold text-white">
            ${stats.totalOrders > 0 ? (stats.totalRevenue / stats.totalOrders).toFixed(2) : '0.00'}
          </h2>
        </div>

        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
          <div className="flex justify-between items-center text-purple-400">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              AI Conversion Boost
            </span>
            <Cpu className="w-5 h-5" />
          </div>
          <h2 className="text-2xl font-extrabold text-white">+18.4%</h2>
        </div>

        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-2">
          <div className="flex justify-between items-center text-emerald-400">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Customer Retention
            </span>
            <TrendingUp className="w-5 h-5" />
          </div>
          <h2 className="text-2xl font-extrabold text-white">74.2%</h2>
        </div>
      </div>

      {/* Analytics Chart Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-card rounded-2xl p-6 border border-slate-800 space-y-4">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-indigo-400" />
            <span>Monthly Revenue Trajectory</span>
          </h3>

          <div className="h-48 bg-slate-950/60 rounded-xl border border-slate-800 p-4 flex items-end justify-between gap-2">
            {/* Visual Bar Graph */}
            {[45, 60, 52, 78, 85, 92, 100].map((val, idx) => (
              <div key={idx} className="flex-1 flex flex-col items-center gap-1 group">
                <div
                  style={{ height: `${val}%` }}
                  className="w-full bg-gradient-to-t from-indigo-600 to-purple-500 rounded-t-lg group-hover:opacity-80 transition"
                />
                <span className="text-[10px] text-slate-500">M{idx + 1}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="glass-card rounded-2xl p-6 border border-slate-800 space-y-4">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Cpu className="w-4 h-4 text-purple-400" />
            <span>AI Recommendation Match Click-Through</span>
          </h3>

          <div className="h-48 bg-slate-950/60 rounded-xl border border-slate-800 p-6 flex flex-col justify-center text-center space-y-2">
            <span className="text-3xl font-black text-indigo-300">4,280</span>
            <p className="text-xs text-slate-400">
              Total recommendation clicks generated by ShopAI discovery engine
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
